### PR TITLE
Update info about using Siri to turn on / off switch control

### PR DESCRIPTION
**Pull request by fbernutz**
# What does this PR do?

In some newer iOS versions, it is working fine to use Siri to turn on or off switch control. I could not find iOS release notes on information in which iOS version this was added, but it's working in iOS 17.6.1. Since this makes turning on and off switch control immensely easier, I would like to add it to the docs even though it might not be working for some users with lower iOS version. 

## How do you test this PR?

Test link: https://appt.org/en/docs/ios/features/switch-control#enable-switch-control and https://appt.org/en/docs/ios/features/switch-control#disable-switch-control

### CODE REVIEW

**Comment by JJdeGroot** [comment]
This doesn't work on iOS 17.5.1. Currently updating to 17.6.1.

**Comment by JJdeGroot** [comment]
It doesn't work for me on iOS 17.6.1, both in Dutch and English.

Can you make a video showcasing that how it works on your device, @fbernutz ? Thanks!

**Comment by fbernutz** [comment]
> It doesn't work for me on iOS 17.6.1, both in Dutch and English.
> 
> Can you make a video showcasing that how it works on your device, @fbernutz ? Thanks!

I press the power button to use Siri and say "Turn on Switch Control", later I say "Turn off Switch Control":

https://github.com/user-attachments/assets/218a8e92-53e2-4c9c-a74e-45943020a43e

My phone is set to English language + region is Germany, Siri language is set to English (UK). I have an iPhone 13 Pro with iOS 17.6.1. Switch Control scanning style is auto, control mode is "Item Mode", I have setup one switch with Full Screen to select item.

**Comment by JJdeGroot** [comment]
Thanks for sharing @fbernutz 

Maybe you can use that shortcut because you have an accessibility shortcut sets for Switch Control. Or maybe I can't use it because Switch Control hasn't been set-up properly or something.

I'm going to update to iOS 18 later today and will give it another try. But considering it works on your device, either way it's a good addition to the article.

**Review by JJdeGroot — APPROVED** [review]

**Comment by JJdeGroot** [comment]
Hi @fbernutz , it still doesn't work for me - but I think it's good info to have for those that can use it. Just merged.

**Pull request merged**
